version:'3.4'

services:
    s_rabbitmq:
        container_name:rabbitmq
        image:rabbitmq:3.12-management
        ports:
            --5672:5672
            --15672:15672
        volumes:
            --rabbitmq:/var/lib/rabbitmq
volumes:
    rabbitmq: